### ISSUE TITLE
Possible bug with Trent

### ISSUE THREAD

**Issue by ALFAIthildur** [Skitia/Wings#1]
https://www.gibberlings3.net/forums/topic/33427-wings/

Enjoying the mod so far but seem to have run into a bug: after discovering the gem in the graveyard district (and having it crumble leaving nothing but the note), I returned to Trent to report what happened, but he 'has nothing to say to you'. Seems like a trigger is missing/didn't increment properly, and/or (guessing by the contents of the ominous note X3WLet4) a critical encounter/event hasn't triggered.

 

The global "X3WINGSQUEST" is at 16, X3WFAIL is 2, and X3WINGSTIMER is 541445

 

Tried an earlier save and got the gem successfully from the graveyard, fought off the ambush, and returned to Trent (slight delay having to fight off ambushes). Same results, he has nothing to say. Main quest global is the same (16), X3WFAIL is 1 and timer is 540678

**Comment by ALFAIthildur** [comment]
Managed to continue the quest by going straight to Crooked Crain; seems like there's missing events as Trent is obviously supposed to disappear but he remains where he spawned (in my case was in docks) with nothing to say.
Once party arrived at crooked crane things proceeded smoothly enough (though dialog/RP wise it's a little odd obviously) until the confrontation with Praxis, where 2 oddities took place:

1. This one's a bit nitpicky, but... since it's rather obvious the party's likely walking into a trap I cast Invisibility 10foot radius so the entire party was invis. The cutscene proceeded as if speaking NPCs could see/sense the arrival of the party, but when combat starts they are completely oblivious. Probably could use a tweak so that at least Laravyl and possibly Praxis both have some means of seeing/detecting invisibility, or better yet (probably more plausible) have their mage cast true sight or have a skilled thief detecting illusions.
2. CreateCreature("X3WFE",[559.1368],NE) failed to create the creature, as the cre file does not exist. Looking through the folder both in my installation and here in github shows that there is no such cre file. [edit] I'm guessing this is the prisoner in the other cell that Trent refers to in his dialogue, since there was no one there.

**Comment by Skitia** [comment]
Thanks for catching this!

Can you let me know if this is EET or standard? For your first bug report, I can't replicate it at all. It only relies on X3WINGSQUEST being at 16 and Global("X3WAmbushSpawn","AR0022") being at 0. My Trent disappears after that and then there is an encounter.

Besides version, it's possible that Trent was stuck doing another action and could never get to the destroy self-one...or that there were two and it destroyed one.

I've uploaded the fix for #2 and I'll figure out how I want to implement #1.

**Comment by ALFAIthildur** [comment]
I'm on a BG2EE install currently, not EET

Trent did spawn in at a rather potentially awkward spot (just outside the main shadow thief compound) which made me wonder if something about that location was causing an issue; I did not see a duplicate Trent.

However I think the issue may be something else -I presume you're refering to the snippet:
IF
	Global("X3WingsQuest","GLOBAL",16)
	Global("X3WAmbushSpawn","AR0022",0)  // Crooked Crane 2nd Floor
THEN
	RESPONSE #100
		SetGlobal("X3WAmbushSpawn","AR0022",1)  // Crooked Crane 2nd Floor
		ActionOverride("X3WTrent",DestroySelf())
		CreateCreature("X3WML",[844.406],NW)  // Slaver Lieutenant
		CreateCreature("X3WFME",[541.389],NE)  // Slaver
		CreateCreature("X3WFRE",[907.354],NE)  // Slaver
		CreateCreature("X3WFRM",[851.304],NE)  // Slaver
		CreateCreature("X3WFRM",[707.401],NE)  // Slaver
		CreateCreature("X3WRE",[581.120],SW)  // Slaver
		CreateCreature("X3WCE",[781.440],NW)  // Slaver
		CreateCreature("X3WFMM",[678.351],NW)  // Slaver
		CreateCreature("X3WFMM",[610.323],NW)  // Slaver
END

If so the problem seems to be that it's in AR0022.bcs, which as I understand it means it does not fire until AR0022 is loaded, which is why I was able to get the quest to proceed when I went straight to AR0022... but until then Trent remains where he spawned in.

As for #1 it's more a suggestion, not a bug; it just seems like it's odd that the cutscene ignores invisibility but once combat starts they can't see you. I'm sure there's other cutscenes out there (including some of bioware's own) that function the same way.

thanks for your work on this; I think it's one of the better NPC mods out there and am glad to see it get the support and love it deserves.

**Comment by ALFAIthildur** [comment]
As for #2, I should clarify; I thought that the missing/mistyped cre file was the 'winged elf' in the other cell that Trent's dialog option #2 mentions when he's rescued.
I didn't peek too closely at the script beyond the above snippet (trying to spare myself more spoilers.... a little disappointed that I spoiled myself a surprise by looking as much as I did and realizing who that winged elf was supposed to be!) but my guess is that he's not supposed to be there unless the plot hook starting in Immesvile has already begun? If so then the dialog reply option when conversing with Trent shouldn't be available if the party has never been to Immesvile, I would think.

It would've been a nice surprise to run into him there, definitely, but seems like the likelihood of getting to Immesvile before triggering the Trent/Praxis quest would be pretty low for most players, but then again, maybe I'm completely wrong on the sequence of events/said NPC appearing in the slavers compound etc.

**Comment by ALFAIthildur** [comment]
One more note; even though I managed to get the quest to proceed by going straight to Crooked Crane, that didn't quite tidy everything up; in spite of the script for AR0022 line that indicates ActionOverride("X3WTrent",DestroySelf()) the original Trent was still hanging around where we first encountered him (in the Docks by the Thieves' compound) still with no dialog, long after we said goodbye to him after wrapping things up in the slavers' compound.
There's also the matter of a missing event somewhere along the way where the party finds out Trent has vanished; no such event ever occurred, even though journal entries indicate it did.

**Comment by Skitia** [comment]
On the Winged Elf: There's a chance it won't happen depending on how you play, so there's another sequence that can happen if that one didn't specifically for those players in chapter 6. Either one occurring is key for one last encounter in ToB. Still, I like the one in the slaver compound the most.

The game can't destroy Trent if he isn't in the area, that's why the dock one persists. When I publish 1.00 he should never go to the docks and actually go the inn, so it should correctly destroy him.

The ambush has dialogue that alerts the party they went missing (Then Aerie should have a conversation post ambush or post letter acquiring.) Again, with 1.00 it should all work correctly!

**Comment by ALFAIthildur** [comment]
Great, thanks for the comments/upcoming fixes. I just hope I haven't missed anything significant yet with the winged one in ch2 (or messed things up for later chapters).

**Comment by Skitia** [comment]
No problem! 

I'll close this, I've updated the two NPCs I wanted to use true sight so they aren't totally blind, and I'll release Canidate 1.00 this weekend after seeing if there area ny other bugs.
