### ISSUE TITLE
Dialog assigned to wrong characters

### ISSUE THREAD

**Issue by ALFAIthildur** [Skitia/Wings#3]
I've noticed a couple of instances so far where a bit of dialog is spoken by the wrong character. For example, when Trent first introduces himself to the party (or might be the 2nd conversation; it's pretty early on regardless) the following line is obviously meant to be spoken by Trent, but Minsc in my case ends up speaking it:

"Minsc understands little of this dark business, but oh does it make Boo twitch... (etc)" (correctly spoken by Minsc)
"I've been trying to listen on them without getting caught, and I've recently gotten word of some artifact..." (obviously meant for Trent, but Minsc says this, as well as the next paragraph:)
"Praxis was making an arrangement for the artifact with..." etc

There's at least one other occasion, though I can't remember the exact line; it's when the confrontation with the would be ambush takes place in Immesvale - as best as I can remember, a certain gnome says a few lines, then Minsc replies, then says a couple of lines that seem to be meant for the gnome.

**Comment by Skitia** [comment]
Awesome, I found both and fixed it. I'll be uploading all of these fixes tomorrow as 1.0 so this is good timing.
